;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				beginning-of-visual-line
				evil-append
				evil-backward-char
				evil-backward-word-begin
				evil-change
				evil-delete
				evil-delete-char
				evil-digit-argument-or-evil-beginning-of-line
				evil-end-of-line
				evil-force-normal-state
				evil-forward-char
				evil-forward-word-begin
				evil-inner-paren
				evil-inner-tag
				evil-insert
				evil-mouse-drag-region
				evil-next-line
				evil-normal-state
				evil-previous-line
				evil-repeat-pop
				evil-visual-char
				))

(setq mc/cmds-to-run-once
      '(
				))
